spring.application.name=FitnessTracker
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=myFitnessTracker
server.port=8082
spring.data.mongodb.uri=mongodb+srv://prathameshlodekar:g920SORcyrsNGM2U@fitnesstracker.ewgrbh5.mongodb.net/?retryWrites=true&w=majority&appName=fitnessTracker8
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# Cache static resources for 30 days
spring.web.resources.cache.cachecontrol.max-age=2592000
spring.web.resources.cache.cachecontrol.cache-public=true

google.api.key=${GOOGLE_API_KEY}





