package com.example.FitnessTracker.Controller;

import com.example.FitnessTracker.Services.AskServices;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Controller
public class AskController {

    @Autowired
    private AskServices askServices;

    @GetMapping("/AskAi")
    public String askAi() {
        return "askAi";
    }

//    @PostMapping("/AskAiPlan")
//    public String handleWorkoutForm(@RequestParam Map<String, String> formData, Model model) {
//        // Extract form fields:
//        String goal = formData.get("goal");
//        String experience = formData.get("experience");
//        String workoutDays = formData.get("workout");
//
//        // Build your AI prompt or process data here
//        String prompt = String.format("Create a %s day workout plan for a %s experience user with goal %s.",
//                workoutDays, experience, goal);
//
//        // Call your AI service with `prompt` and get result (String)
//        String workoutPlan = askServices.askGemini(prompt);
//
//        // Add workoutPlan to model for showing in Thymeleaf page
//        model.addAttribute("workoutPlan", workoutPlan);
//
//        // Return a view name (e.g., show plan on a 'workoutplan' template)
//        return workoutPlan;
//    }

    // For AJAX fetch POST (JS-based dynamic fetch, e.g. from your ask.js file)
    @PostMapping(value = "/AskAiPlanAjax", produces = "text/html")
    @ResponseBody
    public  String handleWorkoutFormAjax(@RequestBody Map<String, String> formData) {

        String goal = formData.getOrDefault("goal", "unspecified");
        String experience = formData.getOrDefault("experience", "unspecified");
        String workoutDays = formData.getOrDefault("workout", "unspecified");



        String prompt = String.format(
                "Generate a workout plan for %s days, tailored to a %s experience level user with the goal of %s. Return the result in HTML format, including only the content that goes inside the <body> tag (do not include the <body> tag itself or any other HTML boilerplate). Use appropriate <h1>, <h2>, etc., tags for headings. Present the daily workouts in a table format styled using Bootstrap classes (e.g., table, table-striped, etc.).Don't include the note at the ending which is generated by gemini about bootstrap and make the contents inside the table white color",
                workoutDays, experience, goal);

        String workoutPlan = askServices.askGemini(prompt);

        // Remove leading ```
        workoutPlan = workoutPlan.replaceAll("^```json\\s*", "");

        // Remove trailing ```
        workoutPlan = workoutPlan.replaceAll("\\s*```$", "");

//        System.out.println(workoutPlan);

        return workoutPlan; // Only the AI text, for AJAX calls via fetch
    }

}
