package com.example.FitnessTracker.Controller;

import com.example.FitnessTracker.Services.AskServices;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Controller
public class AskController {

    @Autowired
    private AskServices askServices;

    @GetMapping("/AskAi")
    public String askAi() {
        return "askAi";
    }

    // For AJAX fetch POST (JS-based dynamic fetch, e.g. from your ask.js file)
    @PostMapping(value = "/AskAiPlanAjax", produces = "text/html")
    @ResponseBody
    public  String handleWorkoutFormAjax(@RequestBody Map<String, String> formData) {

        String goal = formData.getOrDefault("goal", "unspecified");
        String experience = formData.getOrDefault("experience", "unspecified");
        String workoutDays = formData.getOrDefault("workout", "unspecified");



        String prompt = String.format(
                "Generate a workout plan for %s days, tailored to a %s experience level user with the goal of %s. Return the result in HTML format, including only the content that goes inside the <body> tag (do not include the <body> tag itself or any other HTML boilerplate). Use appropriate <h1>, <h2>, etc., tags for headings. Present the daily workouts in a table format styled using Bootstrap classes (e.g., table, table-striped, etc.).Don't include the note at the ending which is generated by gemini about bootstrap and make the contents inside the table white color",
                workoutDays, experience, goal);

        String workoutPlan = askServices.askGemini(prompt);

        // Remove leading ```
        workoutPlan = workoutPlan.replaceAll("^```json\\s*", "");

        // Remove trailing ```
        workoutPlan = workoutPlan.replaceAll("\\s*```$", "");


        return workoutPlan; // Only the AI text, for AJAX calls via fetch
    }

}
